### ISSUE TITLE
how to register two point clouds?

### ISSUE THREAD

**Issue by tiexuedanxin** [qiaozhijian/VCR-Net#1]
Hello, can your approach make registration between the point clouds, which captured by sensor from different view (that means the two point cloud have overlapped with each other to some degree).IF ok could you write a tutorial on how to use your code quickly to register unseen real point cloud, when given two point clouds with the format .ply or .pcd.

**Comment by qiaozhijian** [comment]
try to test model not train
and replace the Dataloader iteration with your point cloud in the same format

**Comment by tiexuedanxin** [comment]
> try to test model not train
> and replace the Dataloader iteration with your point cloud in the same format

hello, I can send my data to you, Could you write a demo code?

**Comment by qiaozhijian** [comment]
Sorry, I'm not convenient

**Comment by tiexuedanxin** [comment]
> Sorry, I'm not convenient

hello, Is your approach need to train a new model on my own data and use the trained model to test, I don't have the data to train the model, because I just have some real data captured by scanner from different views which need to register. I don't know how to convert my own data with format ".pcd" or "ply" to the format ".h5".

**Comment by qiaozhijian** [comment]
I think you should retrain it with your dataset.
pcd or ply is not necessary.  Just input point cloud into network.
A example is as follows,
```
def vcrnet():
    raw = np.load('pcl.npy')
    euler_ab = [0.0, 0.0, 90.0]
    rotation_ab = R.from_euler('zyx', euler_ab, degrees=True)
    raw = rotation_ab.apply(raw).T
    translation_ab = np.array([0.0, 0.0, 0.0])
    raw = raw + np.expand_dims(translation_ab, axis=1)
    raw = raw.T

    src = cutPcl(raw, point=np.asarray([-1, -1, -1]).reshape(1, -1))
    tgt = cutPcl(raw, point=np.asarray([1, 1, 1]).reshape(1, -1)).T
    euler_ab = [12.0, 20.0, 25.0]
    rotation_ab = R.from_euler('zyx', euler_ab, degrees=True)
    tgt = rotation_ab.apply(tgt.T).T
    translation_ab = np.array([0.1, 0.2, 0.3])
    tgt = tgt + np.expand_dims(translation_ab, axis=1)
    src = torch.tensor(src, dtype=torch.float32).cuda().unsqueeze(0).transpose(1, 2).contiguous()
    tgt = torch.tensor(tgt, dtype=torch.float32).cuda().unsqueeze(0)

    args, net = para()
    srcK, src_corrK, rotation_ab_pred, translation_ab_pred, rotation_ba_pred, translation_ba_pred = vcrnetIter(
        net, src, tgt, iter=3)

    # transformed_tgt = torch.matmul(rotation_ba_pred, tgt) + translation_ba_pred.unsqueeze(2)
    # plot3d2(src, transformed_tgt)

    tgt = tgt.detach().cpu().numpy()
    src = src.detach().cpu().numpy()
    rotation_ab_pred = rotation_ab_pred.detach().cpu().numpy()
    translation_ab_pred = translation_ab_pred.detach().cpu().numpy()
    T = np.eye(4)
    T[:3, :3] = rotation_ab_pred
    T[:3, 3] = translation_ab_pred.squeeze()

    return src.squeeze(0).T, tgt.squeeze(0).T, T
```

**Comment by tiexuedanxin** [comment]
> I think you should retrain it with your dataset.
> pcd or ply is not necessary. Just input point cloud into network.
> A example is as follows,
> 
> ```
> def vcrnet():
>     raw = np.load('pcl.npy')
>     euler_ab = [0.0, 0.0, 90.0]
>     rotation_ab = R.from_euler('zyx', euler_ab, degrees=True)
>     raw = rotation_ab.apply(raw).T
>     translation_ab = np.array([0.0, 0.0, 0.0])
>     raw = raw + np.expand_dims(translation_ab, axis=1)
>     raw = raw.T
> 
>     src = cutPcl(raw, point=np.asarray([-1, -1, -1]).reshape(1, -1))
>     tgt = cutPcl(raw, point=np.asarray([1, 1, 1]).reshape(1, -1)).T
>     euler_ab = [12.0, 20.0, 25.0]
>     rotation_ab = R.from_euler('zyx', euler_ab, degrees=True)
>     tgt = rotation_ab.apply(tgt.T).T
>     translation_ab = np.array([0.1, 0.2, 0.3])
>     tgt = tgt + np.expand_dims(translation_ab, axis=1)
>     src = torch.tensor(src, dtype=torch.float32).cuda().unsqueeze(0).transpose(1, 2).contiguous()
>     tgt = torch.tensor(tgt, dtype=torch.float32).cuda().unsqueeze(0)
> 
>     args, net = para()
>     srcK, src_corrK, rotation_ab_pred, translation_ab_pred, rotation_ba_pred, translation_ba_pred = vcrnetIter(
>         net, src, tgt, iter=3)
> 
>     # transformed_tgt = torch.matmul(rotation_ba_pred, tgt) + translation_ba_pred.unsqueeze(2)
>     # plot3d2(src, transformed_tgt)
> 
>     tgt = tgt.detach().cpu().numpy()
>     src = src.detach().cpu().numpy()
>     rotation_ab_pred = rotation_ab_pred.detach().cpu().numpy()
>     translation_ab_pred = translation_ab_pred.detach().cpu().numpy()
>     T = np.eye(4)
>     T[:3, :3] = rotation_ab_pred
>     T[:3, 3] = translation_ab_pred.squeeze()
> 
>     return src.squeeze(0).T, tgt.squeeze(0).T, T
> ```

It is impossible to get a large labeled dataset to train the network, there is some data captured from different view which need to register, besides no other data.
