### ISSUE TITLE
RuntimeError: svd_cuda: the updating process of SBDSDC did not converge (error: 2)

### ISSUE THREAD

**Issue by tiexuedanxin** [qiaozhijian/VCR-Net#2]
hello, when I use your code to train the network, the error "RuntimeError: svd_cuda: the updating process of SBDSDC did not converge (error: 2)" occured, Could you give me some advice on how to solve it, thanks very much.

**Comment by qiaozhijian** [comment]
try: 
u, s, v = torch.svd(H[i]+0.00001)
add a small value onto H[i]
