### ISSUE TITLE
Where can I find the KITTI dataset?

### ISSUE THREAD

**Issue by wangyujiewj** [qiaozhijian/VCR-Net#4]
Hello, I'm very interested in this work about point cloud registration, I trained and tested your released model on the ModelNet40 dataset, but I cannot do experiments on the KITTI dataset as your description in this paper, because I cannot find the KITTI dataset. Could you release the KITTI dataset? Thank you very much!

**Comment by qiaozhijian** [comment]
#3 You can refer to this issue. Just read the point cloud of kitti, downsample them to 4096 or 1024 according to your GPU memory and transform them to make new registration pairs.

**Comment by wangyujiewj** [comment]
> #3 You can refer to this issue. Just read the point cloud of kitti, downsample them to 4096 or 1024 according to your GPU memory and transform them to make new registration pairs.

Thank you very much! Sorry to bother you. I should first look over the closed issues.
